name: Build and Release Electron App

on:
  push:
    branches: [ main, master, featues/newcss ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-13, windows-latest]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Nuxt app
      run: npm run build

    - name: List dist-electron directory

      if: always()
      shell: bash
      run: |
        echo "Listing dist-electron contents..."
        ls -la dist-electron/ || echo "dist-electron directory not found"
        find . -name "*.dmg" -o -name "*.exe" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "*.msi" -o -name "*.zip" | head -10

    - name: Upload macOS artifacts
      if: matrix.os == 'macos-13'
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: dist-electron/*.dmg
        if-no-files-found: warn

    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist-electron/*.exe
        if-no-files-found: warn

    # Linux build removed (not in matrix)

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          macos-build/*
          windows-build/*
          linux-build/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
